[package]
name = "ibkr-statement-importer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
futures = "0.3.31"
ibkr-flex-statement = { version = "0.2.0", registry = "invezt-io-registry" }
mongodb = "3.2.3"
serde = "1.0.219"
tokio = "1.44.2"
