services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: trader
      MONGO_INITDB_ROOT_PASSWORD: traders3cr3t!
    volumes: 
      - /data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: trader
      ME_CONFIG_MONGODB_ADMINPASSWORD: traders3cr3t!
      ME_CONFIG_MONGODB_URL: mongodb://trader:traders3cr3t!@mongo:27017/
      ME_CONFIG_BASICAUTH: false
